import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mapa de Argentina - Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[url('/icon.png')] bg-no-repeat bg-cover">
          <div className="container mx-auto h-screen border-x-white border-x-4 border-solid">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
